name: safe_money
description: A mobile application that will help keep track of the accumulation of money will also help predict and calculate an approximate date before reaching a certain amount at the current pace.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.0.4
  floating_action_row: ^0.1.0
  shared_preferences: ^0.5.6
  easy_dialog:
  path_provider: ^1.6.0
  percent_indicator: "^2.1.1"
  url_launcher:

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
